### ISSUE TITLE
Missing config file on new_api branch

### ISSUE THREAD

**Issue by NiallMac** [simonsobs/falafel#14]
Importing utils generates the following error due to a missing config file on the new_api branch.

```
>>> from falafel import utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/u1/m/maccrann/cmb/lensing/code/falafel/falafel/utils.py", line 14, in <module>
    config = io.config_from_yaml(os.path.dirname(os.path.abspath(__file__)) + "/../input/config.yml")
  File "/global/homes/m/maccrann/.conda/envs/lenspipe/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/global/u1/m/maccrann/cmb/lensing/code/falafel/falafel/../input/config.yml'
```

**Comment by msyriac** [comment]
Thanks Niall, a config file was missing. I've pushed it now. You'll need to do the usual of copying input/config_template.yml to input/config.yml and editing it with paths relevant to the system you are on. I'll think about how this can be made more seamless.
